[build]
    base = "./"
    publish = "./dist"
    command = "npm run build"

[dev]
    framework = "#custom"
    command = "npm run dev"
    targetPort = 5000
    port = 8888

[[redirects]]
    from = "/"
    to = "/about"
    status = 200

[[redirects]]
    from = ""
    to = "/about"
    status = 200
