[build]
    base = "./"
    publish = "./dist"
    command = "npm run build"

[dev]
    framework = "#custom"
    command = "npm run dev"
    targetPort = 5000
    port = 8888

[[redirects]]
    from = "https://www.okunskiy.name/*"
    to = "https://boris.okunskiy.name/:splat"
    force = true
    status = 301

[[redirects]]
    from = "https://okunskiy.name/*"
    to = "https://boris.okunskiy.name/:splat"
    force = true
    status = 301

[[redirects]]
    from = "https://boris-okunskiy.netlify.app/*"
    to = "https://boris.okunskiy.name/:splat"
    force = true
    status = 301

[[redirects]]
    from = "/about"
    to = "/"
